#!/bin/bash
# Multi-UE lab reset.  usage: demo_reset_multi.sh [N_UES] [N_ANCHORS]
#
#   N_UES     total UEs to attach            (default 5)
#   N_ANCHORS how many are PINNED to secondary (default 1)
#
# The first (N_UES - N_ANCHORS) UEs get 'steering-rule-both': they start on
# internet-primary and may be steered to internet-secondary and back. The last
# N_ANCHORS get 'steering-rule-secondary': pinned to secondary, unsteerable,
# and there to keep that path MEASURABLE. Without at least one anchor the RATE
# rule cannot compare two paths at all (only one DNAI ever has data), and the
# HEALTH rule can only ever see the abandoned path as UNKNOWN.
#
# Why the split is done in policy and not in routeToLocs: get_authorized_dnais()
# returns a std::set<std::string>, which is SORTED, so listing secondary first
# in the traffic rule does not make a session start there - 'internet-primary'
# always sorts first. The starting path is therefore chosen by which DNAIs the
# PCC rule authorizes at all.
set -u
N=${1:-5}
ANCHORS=${2:-1}
PCF=192.168.70.139:8080
V=/openair-upf/bin/vppctl
# SBI image and its qosmonlist retention, overridable from the environment so a
# new collector build can be deployed without editing this script.
SBI_IMAGE=${SBI_IMAGE:-oai-nwdaf-sbi:qosmon-retain}
QOSMON_RETAIN=${QOSMON_RETAIN:-1000}
# Where the PCF reads its policy decisions from. Override for a different layout.
# NOTE: the PCF loads EVERY file in that directory - never leave a backup there,
# or a stale copy silently overrides entries in the live file.
FED=${FED:-$HOME/oai-cn5g-fed/docker-compose}
POL=${PCF_POLICY_DECISIONS:-$FED/policies/steering/policy_decisions}/policy_decision.yaml
[ -d "$(dirname "$POL")" ] || { echo "PCF policy dir not found: $(dirname "$POL")"; echo "run ./scripts/build.sh fed, or set FED/PCF_POLICY_DECISIONS"; exit 1; }

[ "$N" -ge 2 ] || { echo "need at least 2 UEs"; exit 1; }

# Fail fast on a core that is not up. Without this the script restarts three
# containers that do not exist, waits out three 60 s timeouts, and only then
# fails while creating UEs - so the reported error is a UE error and the real
# cause (no core) is 200 lines up.
for c in vpp-upf oai-smf oai-pcf; do
  sudo docker inspect --type container "$c" >/dev/null 2>&1 || {
    echo "FAIL: container '$c' does not exist - the 5G core is not running."
    echo "      Run ./scripts/deploy/start_core.sh first."; exit 1; }
done
for n in demo-oai-public-net oai-public-access; do
  sudo docker network inspect "$n" >/dev/null 2>&1 || {
    echo "FAIL: network '$n' does not exist - the 5G core is not running."
    echo "      Run ./scripts/deploy/start_core.sh first."; exit 1; }
done
[ "$ANCHORS" -lt "$N" ] || { echo "need at least one steerable UE"; exit 1; }

sess_count(){ sudo docker exec vpp-upf $V show upf session 2>/dev/null | grep -cE "^CP F-SEID"; }
wait_for(){ local desc="$1" tries="$2"; shift 2
  for i in $(seq "$tries"); do eval "$@" >/dev/null 2>&1 && { echo "      ok: $desc"; return 0; }; sleep 2; done
  echo "      TIMEOUT waiting for: $desc"; return 1; }

echo "[1/7] stop traffic, remove SBI and all gnbsim containers"
for i in $(seq 2 20); do sudo docker exec "gnbsim-vpp$i" pkill iperf3 2>/dev/null; done
sudo docker rm -f oai-nwdaf-sbi $(sudo docker ps -aq --filter 'name=gnbsim-vpp') >/dev/null 2>&1
# Force-removing a connected container can leave its network ENDPOINT behind, and
# the next create then fails with "endpoint with name gnbsim-vppN already exists"
# even though no container of that name is listed. Sweep both networks.
for net in demo-oai-public-net oai-public-access; do
  for ep in $(sudo docker network inspect "$net" \
      -f '{{range $k,$v := .Containers}}{{$v.Name}} {{end}}' 2>/dev/null); do
    case "$ep" in gnbsim-vpp*) sudo docker network disconnect -f "$net" "$ep" 2>/dev/null;; esac
  done
done
sudo docker exec vpp-upf tc qdisc del dev n6-3 root 2>/dev/null
sudo docker exec vpp-upf tc qdisc del dev n6-4 root 2>/dev/null

echo "[2/7] generating PCF policy decisions for $N UEs ($((N-ANCHORS)) steerable, $ANCHORS anchored)"
# The PCF matches on supi_imsi. A SUPI with no entry here gets NO DNAI
# authorization at all, so every UE that attaches must be listed.
{
  echo "# GENERATED by demo_reset_multi.sh - do not hand-edit."
  echo "# Restore the 2-UE setup with:"
    echo "#   cp ~/nwdaf-backups/policy/policy_decision.yaml.2ue \\"
    echo "#      ~/oai-cn5g-fed/docker-compose/policies/steering/policy_decisions/policy_decision.yaml"
    echo "# NEVER keep a backup INSIDE policy_decisions/ - the PCF loads EVERY file in"
    echo "# that directory, so a stale copy silently overrides entries in this one."
  for i in $(seq 1 "$N"); do
    SUPI=$(printf '20895%010d' $((32 + i - 1)))
    if [ "$i" -le $((N-ANCHORS)) ]; then RULE=steering-rule-both; else RULE=steering-rule-secondary; fi
    echo "decision_supi$i:"
    echo "  supi_imsi: \"$SUPI\""
    echo "  pcc_rules:"
    echo "    - $RULE"
  done
} > "$POL"
echo "      wrote $POL"

echo "[3/7] restart UPF, then SMF, then PCF"
sudo docker restart vpp-upf >/dev/null
wait_for "vpp-upf healthy" 30 '[ "$(sudo docker inspect -f "{{.State.Health.Status}}" vpp-upf)" = healthy ]'
sudo docker restart oai-smf >/dev/null
wait_for "oai-smf healthy" 30 '[ "$(sudo docker inspect -f "{{.State.Health.Status}}" oai-smf)" = healthy ]'
wait_for "PFCP association up" 30 'sudo docker exec vpp-upf '"$V"' show upf association | grep -q "Node: oai-smf"'
sudo docker restart oai-pcf >/dev/null
wait_for "oai-pcf healthy" 30 '[ "$(sudo docker inspect -f "{{.State.Health.Status}}" oai-pcf)" = healthy ]'

echo "[4/7] start SBI ($SBI_IMAGE, qosmonlist retain=$QOSMON_RETAIN) - AFTER the SMF is stable, BEFORE any UE attaches"
# Too early and its subscription is duplicated; too late and the UP_PATH_CH
# events recording which DNAI each session is on are emitted with no subscriber
# and lost, so DN_PERFORMANCE attributes usage reports to a stale DNAI forever.
sudo docker create --name oai-nwdaf-sbi \
  --network demo-oai-public-net --ip 192.168.70.158 \
  -e SERVER_ADDR=0.0.0.0:8080 -e MONGODB_URI=mongodb://192.168.75.156:27017 \
  -e MONGODB_DATABASE_NAME=testing \
  -e MONGODB_COLLECTION_NAME_AMF=amf -e MONGODB_COLLECTION_NAME_SMF=smf \
  -e AMF_IP_ADDR=http://192.168.70.132:8080 -e AMF_SUBSCR_ROUTE=/namf-evts/v1 \
  -e AMF_API_ROUTE=/test/amf -e AMF_NOTIFICATION_ID=1 \
  -e AMF_NOTIFY_CORRELATION_ID=string -e AMF_NOTIFICATION_FORWARD_ROUTE=/sbi/notification/amf \
  -e AMF_HTTP_VERSION=2 \
  -e SMF_IP_ADDR=http://192.168.70.133:8080 -e SMF_SUBSCR_ROUTE=/nsmf-event-exposure/v1 \
  -e SMF_API_ROUTE=/test/smf -e SMF_NOTIFICATION_ID=2 \
  -e SMF_NOTIFY_CORRELATION_ID=string -e SMF_NOTIFICATION_FORWARD_ROUTE=/sbi/notification/smf \
  -e SMF_HTTP_VERSION=2 -e EVENT_NOTIFY_URI=http://oai-nwdaf-sbi:8080 \
  -e NRF_URI=http://192.168.70.130:8080 -e NRF_HTTP_VERSION=2 \
  -e MONGODB_QOSMON_RETAIN="$QOSMON_RETAIN" \
  "$SBI_IMAGE" >/dev/null
sudo docker network connect --ip 192.168.75.158 oai-nwdaf-net oai-nwdaf-sbi
sudo docker start oai-nwdaf-sbi >/dev/null; sleep 12

echo "[5/7] attaching $N UEs"
for i in $(seq 1 "$N"); do
  NAME="gnbsim-vpp$((i+1))"
  MSIN=$(printf '%010d' $((32 + i - 1)))
  IP70=192.168.70.$((141 + i))
  IP72=192.168.72.$((141 + i))
  printf "      %-14s MSIN ...%s  " "$NAME" "$MSIN"
  sudo docker create --name "$NAME" --privileged \
    --network demo-oai-public-net --ip "$IP70" \
    -e MCC=208 -e MNC=95 -e SST=222 -e SD=000005 -e DNN=default \
    -e NRCellID="$i" -e GNBID="$((i+4))" -e TAC=0x00a000 -e PagingDRX=v32 \
    -e MSIN="$MSIN" -e RoutingIndicator=1234 \
    -e KEY=0C0A34601D4F07677303652C0462535B \
    -e OPc=63bfa50ee6523365ff14c1f45f88737d \
    -e IMEISV=35609204079514 -e ProtectionScheme=null \
    -e DEREG_AFTER=86400 -e RANUENGAPID=0 -e USE_FQDN=no \
    -e NGAPPeerAddr=192.168.70.132 \
    -e GTPuLocalAddr="$IP72" -e GTPuIFname=eth1 \
    -e URL=http://www.asnt.org:8080/ gnbsim:latest >/dev/null
  sudo docker network connect --ip "$IP72" oai-public-access "$NAME"
  sudo docker start "$NAME" >/dev/null
  # Serialise attaches: a burst of simultaneous registrations makes the AMF
  # drop some, and a UE that half-attaches is harder to spot than one that
  # never does.
  for t in $(seq 40); do [ "$(sess_count)" -ge "$i" ] && break; sleep 2; done
  [ "$(sess_count)" -ge "$i" ] && echo "attached" || echo "FAILED"
done

echo "[6/7] settling"; sleep 15

echo "[7/7] done"
echo
echo "=================== RESULT ==================="
sudo docker exec vpp-upf $V show upf session 2>/dev/null | python3 -c '
import sys,re,subprocess
env=subprocess.run(["sudo","docker","inspect","vpp-upf","--format","{{range .Config.Env}}{{println .}}{{end}}"],capture_output=True,text=True).stdout
cfg=dict(l.split("=",1) for l in env.splitlines() if "=" in l)
m={cfg[f"IF_{i}_NWI"]:cfg[f"IF_{i}_DNAI"] for i in range(1,32) if cfg.get(f"IF_{i}_TYPE")=="N6"}
# Collect per SEID rather than depending on the order of lines inside a PDR:
# the previous version required Core -> Network Instance -> IPv4 in sequence and
# dropped any session that did not match, silently.
seid=None; ip={}; nwi={}; order=[]
for line in sys.stdin:
    s=line.strip()
    mm=re.match(r"^CP F-SEID.*\((\d+)\)",s)
    if mm:
        seid=mm.group(1)
        if seid not in order: order.append(seid)
        continue
    if seid is None: continue
    if s.startswith("IPv4 address: 12.") and seid not in ip:
        ip[seid]=s.split(":",1)[1].strip()
    if s.startswith("Network Instance:"):
        v=s.split(":",1)[1].strip()
        if v in m and seid not in nwi: nwi[seid]=v
for k in order:
    print("  SEID %-3s %-10s %s"%(k, ip.get(k,"?"), m.get(nwi.get(k,""),"?")))'
SUBS=$(sudo docker logs oai-smf 2>&1 | awk '/\[start\] Started/{c=0} /Handle an Event Exposure Subscription Request/{c++} END{print c+0}')
echo "  sessions=$(sess_count) (expect $N)   subscriptions=$SUBS (expect 1)"
# Steerability: how many sessions have a GOVERNING rule authorizing BOTH N6
# DNAIs. Counted within ONE poll cycle - every session logs a decision on every
# poll, so counting over a time window multiplies by the number of polls.
DEC=$(sudo docker logs oai-smf --since 60s 2>&1 | grep 'per-session decision')
LAST=$(echo "$DEC" | tail -1 | grep -oP '^\[\K[^]]+')
STEERABLE=$(echo "$DEC" | grep -F "$LAST" \
  | grep -cP 'authorized \{[^}]*internet-primary[^}]*internet-secondary[^}]*\}')
TOTAL=$(echo "$DEC" | grep -cF "$LAST")
if [ "$STEERABLE" = "$((N-ANCHORS))" ]; then
  echo "  steerable: $STEERABLE/$TOTAL sessions authorize both N6 DNAIs - OK"
else
  echo "  steerable: $STEERABLE/$TOTAL (expected $((N-ANCHORS))) *** CHECK THIS ***"
  echo "    if 0, decisions have not been logged yet - re-check in 20s"
fi
echo "=============================================="
