#/*
# * SPDX-License-Identifier: LicenseRef-CSSL-1.0
# */

ARG BUILD_IMAGE=golang:1.19-alpine
ARG TARGET_IMAGE=alpine:3.18

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM $BUILD_IMAGE AS oai-nwdaf-sbi-build
WORKDIR /oai/nwdaf/sbi
ENV CGO_ENABLED=0
COPY go.* ./
RUN go mod download
COPY . ./
RUN go build -o bin/oai-nwdaf-sbi cmd/oai-nwdaf-sbi/main.go

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM $TARGET_IMAGE AS oai-nwdaf-sbi
RUN apk update && apk add -U net-tools curl bash
COPY --from=oai-nwdaf-sbi-build /oai/nwdaf/sbi/bin/oai-nwdaf-sbi ./
COPY .env ./
EXPOSE 8080/tcp
ENTRYPOINT ["./oai-nwdaf-sbi"]
