/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

import (
	"context"
	"net/http"
)

// ------------------------------------------------------------------------------
// NWDAFContextDocumentApiService is a service that implements the logic for the NWDAFContextDocumentApiServicer
type NWDAFContextDocumentApiService struct {
}

// ------------------------------------------------------------------------------
// NewNWDAFContextDocumentApiService creates a default api service
func NewNWDAFContextDocumentApiService() NWDAFContextDocumentApiServicer {
	return &NWDAFContextDocumentApiService{}
}

// ------------------------------------------------------------------------------
// GetNwdafContext - Nnwdaf_AnalyticsInfo_ContextTransfer (TS 23.288 clause
// 7.3.3, procedure in clause 6.1B.4).
//
// NOT IMPLEMENTED, and now says so.
//
// This method previously returned `Response(200, ContextData{})` - an EMPTY
// body with a SUCCESS code. That is worse than not implementing it: a peer
// NWDAF performing an analytics context transfer is told "success, here is the
// context" and silently proceeds on empty state, losing every pending and
// historical analytics context it asked for.
//
// ContextTransfer is meaningful only between NWDAF instances (TS 23.288
// Table 7.1-1 lists NWDAF as the sole consumer) and this deployment runs one
// NWDAF, so implementing clause 6.1B.4 is out of scope. Returning 501 is the
// honest answer and is what the sibling Transfer operations already do.
//
// CLASSIFICATION: OAI implementation gap -> now Known non-compliance, declared.
func (s *NWDAFContextDocumentApiService) GetNwdafContext(ctx context.Context, contextIds ContextIdList, reqContext RequestedContext) (ImplResponse, error) {
	return ImplResponse{}, newProblem(
		http.StatusNotImplemented, "NOT_IMPLEMENTED",
		"Nnwdaf_AnalyticsInfo_ContextTransfer (TS 23.288 clause 6.1B.4) is not "+
			"implemented by this NWDAF; it is only meaningful between multiple "+
			"NWDAF instances and this deployment runs a single instance")
}
