/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

type EventIdAnyOf string

// List of EventIdAnyOf
const (
	EVENTIDANYOF_LOAD_LEVEL_INFORMATION EventIdAnyOf = "LOAD_LEVEL_INFORMATION"
	EVENTIDANYOF_NETWORK_PERFORMANCE    EventIdAnyOf = "NETWORK_PERFORMANCE"
	EVENTIDANYOF_NF_LOAD                EventIdAnyOf = "NF_LOAD"
	EVENTIDANYOF_SERVICE_EXPERIENCE     EventIdAnyOf = "SERVICE_EXPERIENCE"
	EVENTIDANYOF_UE_MOBILITY            EventIdAnyOf = "UE_MOBILITY"
	EVENTIDANYOF_UE_COMMUNICATION       EventIdAnyOf = "UE_COMMUNICATION"
	EVENTIDANYOF_QOS_SUSTAINABILITY     EventIdAnyOf = "QOS_SUSTAINABILITY"
	EVENTIDANYOF_ABNORMAL_BEHAVIOUR     EventIdAnyOf = "ABNORMAL_BEHAVIOUR"
	EVENTIDANYOF_USER_DATA_CONGESTION   EventIdAnyOf = "USER_DATA_CONGESTION"
	EVENTIDANYOF_NSI_LOAD_LEVEL         EventIdAnyOf = "NSI_LOAD_LEVEL"
	EVENTIDANYOF_SM_CONGESTION          EventIdAnyOf = "SM_CONGESTION"
	EVENTIDANYOF_DISPERSION             EventIdAnyOf = "DISPERSION"
	EVENTIDANYOF_RED_TRANS_EXP          EventIdAnyOf = "RED_TRANS_EXP"
	EVENTIDANYOF_WLAN_PERFORMANCE       EventIdAnyOf = "WLAN_PERFORMANCE"
	EVENTIDANYOF_DN_PERFORMANCE         EventIdAnyOf = "DN_PERFORMANCE"
	// EVENTIDANYOF_TRAFFIC_STEERING_UPF_LOAD is a custom (non-3GPP) analytic ID: AI-driven
	// congestion forecast / recommended-UPF prediction, built on top of NF_LOAD + QoS
	// telemetry. This is a project-specific extension to the standard 3GPP EventId set,
	// not itself defined in TS 29.520. Its engine-routing pattern (dispatching to a
	// bespoke ML microservice) mirrors how ABNORMAL_BEHAVIOUR is wired to
	// oai-nwdaf-engine-ads - that ID itself is a standard 3GPP value, unlike this one.
	EVENTIDANYOF_TRAFFIC_STEERING_UPF_LOAD EventIdAnyOf = "TRAFFIC_STEERING_UPF_LOAD"
)

// AssertEventIdAnyOfRequired checks if the required fields are not zero-ed
func AssertEventIdAnyOfRequired(obj EventIdAnyOf) error {
	return nil
}

// AssertRecurseEventIdAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of EventIdAnyOf (e.g. [][]EventIdAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseEventIdAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aEventIdAnyOf, ok := obj.(EventIdAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertEventIdAnyOfRequired(aEventIdAnyOf)
	})
}
