/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

// AnalyticsMetadataInfo - Contains analytics metadata information required for analytics aggregation.
type AnalyticsMetadataInfo struct {

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	NumSamples int32 `json:"numSamples,omitempty"`

	DataWindow TimeWindow `json:"dataWindow,omitempty"`

	DataStatProps []DatasetStatisticalProperty `json:"dataStatProps,omitempty"`

	// POINTER on purpose: Go's `omitempty` has NO effect on a struct value, so this
	// OPTIONAL attribute was serialised as an empty object on every response. An
	// attribute this NWDAF does not compute must be ABSENT, not present-and-empty -
	// a consumer cannot tell those apart. CLASSIFICATION: OAI implementation gap.
	Strategy *OutputStrategy `json:"strategy,omitempty"`

	// POINTER on purpose: Go's `omitempty` has NO effect on a struct value, so this
	// OPTIONAL attribute was serialised as an empty object on every response. An
	// attribute this NWDAF does not compute must be ABSENT, not present-and-empty -
	// a consumer cannot tell those apart. CLASSIFICATION: OAI implementation gap.
	Accuracy *Accuracy `json:"accuracy,omitempty"`
}

// AssertAnalyticsMetadataInfoRequired checks if the required fields are not zero-ed
func AssertAnalyticsMetadataInfoRequired(obj AnalyticsMetadataInfo) error {
	if err := AssertTimeWindowRequired(obj.DataWindow); err != nil {
		return err
	}
	for _, el := range obj.DataStatProps {
		if err := AssertDatasetStatisticalPropertyRequired(el); err != nil {
			return err
		}
	}
	if obj.Strategy != nil {
		if err := AssertOutputStrategyRequired(*obj.Strategy); err != nil {
			return err
		}
	}
	if obj.Accuracy != nil {
		if err := AssertAccuracyRequired(*obj.Accuracy); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseAnalyticsMetadataInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AnalyticsMetadataInfo (e.g. [][]AnalyticsMetadataInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAnalyticsMetadataInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAnalyticsMetadataInfo, ok := obj.(AnalyticsMetadataInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAnalyticsMetadataInfoRequired(aAnalyticsMetadataInfo)
	})
}
