#/*
# * SPDX-License-Identifier: LicenseRef-CSSL-1.0
# */

ARG BUILD_IMAGE=golang:1.19-alpine
ARG TARGET_IMAGE=alpine:3.18

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM $BUILD_IMAGE AS oai-nwdaf-nbi-analytics-build
WORKDIR /oai/nwdaf/nbi-analytics
ENV CGO_ENABLED=0
COPY go.* ./
RUN go mod download
COPY . ./
RUN go build -o bin/oai-nwdaf-nbi-analytics cmd/oai-nwdaf-nbi-analytics/main.go

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM $TARGET_IMAGE AS oai-nwdaf-nbi-analytics
RUN apk update && apk add -U net-tools curl bash
COPY --from=oai-nwdaf-nbi-analytics-build /oai/nwdaf/nbi-analytics/bin/oai-nwdaf-nbi-analytics ./
COPY .env ./
EXPOSE 8080/tcp
ENTRYPOINT ["./oai-nwdaf-nbi-analytics"]
